---
title: "Burstiness in LDP"
author: " Maddie Meyers and Dan Yurovsky"
date: "`r Sys.Date()`"
output: 
  html_document:
  toc: false
number_sections: false
theme: lumen
toc_float: false
code_folding: hide
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(langcog)
library(stringr) 
library(lme4)
library(directlabels)
library(DT)
library(broom)
library(data.table)
library(ggplot2)
library(forcats)
library(feather)
library(tidytext)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)

theme_dy <- function(base_size = 14) 
{
  theme_bw() +   
    ggplot2::`%+replace%`(ggplot2::theme_bw(base_size = base_size),
                          ggplot2::theme(panel.grid = ggplot2::element_blank(), 
                                         legend.position = "none"))
}

theme_set(theme_dy())
```

## R Markdown

Setting up data
```{r load_data}
# Original data
loaded_subjs <- read_feather("feathers/loaded_subjs.feather")
# Referents and their frequencies
referents <- read_feather("feathers/referents.feather")
# End result of splitting referents and coding modality
coded_responses <- read_feather("feathers/coded_responses.feather")
```


```{r zipfs}
person_freqs <- coded_responses %>%
  group_by(subj, age, person, modality, referent) %>%
  summarise(person_modality_n = n()) %>%
  group_by(subj, age, referent) %>%
  mutate(total_n = sum(person_modality_n)) 

ranks <- person_freqs %>%
  arrange(subj, age, desc(total_n)) %>%
  distinct(subj, age, referent, .keep_all = TRUE) %>% 
  group_by(subj, age) %>% 
  mutate(rank = 1:n()) %>%
  select(subj, age, referent, rank)

freq_ranks <- left_join(person_freqs, ranks)


ggplot(filter(freq_ranks, modality != "both"), 
       aes(x = rank, y = person_modality_n, 
                  color = as.factor(age), linetype = modality)) + 
  facet_grid(~person) + 
  #geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() + 
  scale_y_log10() +
  theme_classic()
   

person_zipfs <- freq_ranks %>%  
  filter(modality != "both") %>%
  group_by(person, modality) %>%
  do(tidy(lmer(log(person_modality_n) ~ log(rank)*age + (log(rank) + age|subj), data = .))) 


ggplot(filter(person_zipfs, term %in% c("(Intercept)", "age", "log(rank)", "log(rank):age")),
       aes(x = modality, y = estimate, color = person)) + 
  facet_wrap(~ term, scales = "free") + 
  geom_hline(yintercept = 0, lty = 2) + 
  geom_pointrange(aes(ymin = estimate-std.error, ymax = estimate+std.error),
                      position = position_dodge(.5)) + 
  theme_bw()

person_zipfs <- freq_ranks %>%  
  filter(modality != "both") %>%
  group_by(person, modality) %>%
  do(tidy(lmer(log(person_modality_n) ~ log(rank)*age + (log(rank) + age|subj), data = .))) 


ggplot(filter(person_zipfs, term %in% c("(Intercept)", "age", "log(rank)", "log(rank):age")),
       aes(x = modality, y = estimate, color = person)) + 
  facet_wrap(~ term, scales = "free") + 
  geom_hline(yintercept = 0, lty = 2) + 
  geom_pointrange(aes(ymin = estimate-std.error, ymax = estimate+std.error),
                      position = position_dodge(.5)) + 
  theme_bw()
```


```{r intervals}
intervals <- coded_responses %>%
  group_by(subj, age, referent) %>%
  arrange(time) %>%
  summarise(freq = n(), times = paste0(diff(as.numeric(time)), collapse = " ")) %>%
  unnest_tokens(diff, times) %>%
  mutate(diff = as.numeric(diff)) %>%
  group_by(subj, age) %>%
  mutate(total_refs = n(),
         predicted = total_refs/freq) %>%
  group_by(age, subj, freq, referent)

intervals %>%
  group_by(freq, age, subj, referent) %>%
  summarise(diff = median(diff-predicted)) %>%
  summarise(diff = mean(diff)) %>%
  summarise(diff = mean(diff)) %>%
  ggplot(aes(x = freq, y = diff, color = as.factor(age))) + 
    geom_point() + 
    geom_smooth(se = FALSE) + 
    scale_x_log10() + 
  geom_hline(yintercept = 0, lty = 2) +
  # scale_y_log10() +
    theme_bw()


diff_lm <- lmer((diff-predicted) ~ log(freq) + age + log(freq)*age + (log(freq)|subj), 
                data = intervals)
```

For making gleitman plots
```{r}
runs <- coded_responses %>%
  select(subj, age, referent, time) %>%
  arrange(subj, age, referent, time) %>%
  group_by(subj, age, referent) %>%
  mutate(diff = time-lag(time)) %>%
  filter(diff < 10 & diff > 1)

fixed_runs <- map(1:100, function(row) {
  times <- 1:(runs[row,]$diff-1) + runs[row,]$time
  
  data_frame(time = times, subj = runs[row,]$subj, age = runs[row,]$age, 
             referent = runs[row,]$referent)}) %>%
  bind_rows() %>%
  bind_rows(runs)
```

```{r}
gleit<-fixed_runs %>%
  filter(subj==29, age==22)#arbitrary choice

ggplot(gleit, aes(x = as.factor(time), y = referent)) + 
  geom_tile(color = "black") + 
  theme(legend.position = "bottom") 

gleit_order <- gleit %>%
  ungroup() %>%
  group_by(referent) %>%
  arrange(time) %>%
  slice(1) %>%
  arrange(time) 

gleit_ordered <- gleit %>%
  mutate(referent = factor(referent, levels = gleit_order$referent))

ggplot(gleit_ordered, aes(x = as.factor(time), y = referent)) + 
  geom_tile(fill = "black", color = "white") + 
  theme(legend.position = "none")+
  scale_x_discrete(breaks= c(seq(from = 1, to = 1000, by = 10)))

```

