---
title: "Fixing Gesture Data Mistakes"
output: html_notebook
---
```{r}
library(data.table)
library(tidyverse)
library(feather)
```


```{r establish referent changes}
x1<-c("ahir", "ardvark", "at", "batteries", "bbug", "beans", "bicycle", "boo", "boo_boo", "brown_page", "butterly", "caker", "CD", "cerea", "chick", "chicken_nugget, french_fry", "chik", "chil", "chld", "chiristmas_tree", "cirle", "digger", "dump_truck", "eg", "fae", "fiit", "fire_engine", "garbgage", "girlg", "grandma", "hild", "hippo", "ice_crema", "jackbot", "jacker", "jack_box", "key, child", "motorcycyle", "mushrooom", "mustach", "noodel", "oowd", "orange)juice", "pajama", "pajams", "peah", "people", "platn", "play_dough", "pocekt", "potty", "rasin", "refriegerator", "scissor", "seleeve", "wc", "yellow_page", "rubber_ruck", "scrw", "play_dough", "photo_alum", "high_chair", "lolipop", "chair_seat", "dump_truck", "canteloupe", "lucky", "pliers", "experimenter", "hair_tie", "garbage_can", "grandma", "hot_tub", "home", "golf_ball", "cryaon", "winder", "ice_crema", "windowsil", "jackbot", "dol", "rasin", "hold", "chat", "children", "hear", "plato", "plante", "hant", "brown_page", "girly", "arm, sleeve", "nob", "underpants", "goofy", "smiley_face", "muffle", "stairs", "guest_room", "floot", "mother", "shoes", "matter", "lights", "macine", "dipaer", "me", "toilet", "trashcan", "telephone")

y1<-c("hair", "aardvark", " ","battery", "bug", "bean", "bike", "cut", "cut", "page", "butterfly", "cake", "cd", "cereal", "chicken", "chicken_nugget", "chicken", "child", "child", "christmas_tree", "circle", "digger_truck", "dumptruck", "egg", "face", "", "firetruck", "garbage", "girl", "grandmother", "child", "hippopotamus", "ice_cream", "jackpot", "jacket", "jackinthebox", "key", "motorcycle", "mushroom", "mustache", "noodle", "", "orange_juice", "pajamas", "pajamas", "pea", "person", "plate", "playdoh", "pocket", "toilet", "raisin", "refrigerator", "scissors", "sleeve","", "page", "rubber_duck", "screw", "play_doh", "photo_album", "highchair", "lollipop", "highchair", "dumptruck", "cantaloupe", "child", "plier", "", "hairtie", "garbage", "grandmother", "hottub", "", "golfball", "crayon", "crank", "ice_cream", "windowsill", "jackpot", "doll", "raisin", "", "hat", "kid", "", "pluto", "plant", "hand", "", "girl", "arm; sleeve", "knob", "underwear", "", "smile", "muffler", "stair", "guestroom", "floor", "mom", "shoe", "", "light", "machine", "diaper", "", "potty", "garbage", "phone")

referent_changes<-data_frame(referent=x1, fix_referent=y1)
```

```{r fix referent changes}
files <-list.files("ldp_data/coded_data/", 
                   "*.csv", full.names = TRUE)

subjs <- map(files, fread, sep=",", na.strings = c("NA", "")) %>%
  bind_rows() %>%
  mutate(rownum = 1:nrow(.))

fixed_referents <- subjs %>%
  filter(referent %in% referent_changes$referent) %>%
  left_join(referent_changes) %>%
  select(-referent) %>%
  rename(referent = fix_referent) %>%
  bind_rows(filter(subjs, !rownum %in% .$rownum)) %>%
  arrange(rownum) %>%
  select(-rownum)
  
cols <- names(fixed_referents) 

arranged_referents <- fixed_referents %>%
  select_(.dots = cols[c(1:(length(cols)-2), length(cols), length(cols)-1) ])

split_refernts <- arranged_referents %>% split(paste(.$subj, .$session, sep = "_"))

write_referents <- function(df) {
  session <- df[1,"session"]
  subj <- df[1, "subj"]
  
  write_csv(df, paste0("ldp_data/fixed_data/", subj, "_", session, ".csv"), na = "")
}
walk(split_refernts, write_referents)

```

```{r}
files <-list.files("ldp_data/fixed_data/", 
                   "*.csv", full.names = TRUE)

subjs <- map(files, fread, sep=",", na.strings = c("NA", "")) %>%
  bind_rows() %>%
  mutate(age = 10+session*4) %>%
  mutate(time2=rownames(.)) %>%
  group_by(subj, age) %>%
  mutate(time = 1:n()) %>%
  select(time, time2, subj, age, person, spoken_obj, gestured_obj, referent, gloss, chat) 

write_feather(subjs, 'feathers/loaded_subjs_full.feather')
```

