---
title: "referent_presentness"
author: "Maddie Meyers, Dan Yurovsky"
date: "1/16/2018"
output: pdf_document
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(tidyboot)
library(stringr) 
library(lme4)
library(directlabels)
library(DT)
library(broom)
library(data.table)
library(ggplot2)
library(forcats)
library(feather)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)

theme_dy <- function(base_size = 14) 
{
  theme_bw() +   
  ggplot2::`%+replace%`(ggplot2::theme_bw(base_size = base_size),
                          ggplot2::theme(panel.grid = ggplot2::element_blank(), 
        legend.position = "none"))
}

theme_set(theme_dy())
```

## R Markdown


```{r load data}
loaded_subjs<-read_feather('feathers/loaded_subjs_full.feather')
coded_responses<-read_feather('feathers/coded_responses.feather')
referents<-read_feather('feathers/referents.feather')
```

```{r presentness prob}
presentness<-coded_responses %>%
  mutate(ref_predicted=as.numeric(ref_predicted))

summary(presentness$ref_predicted)
#mean presentness value is 0.8671, which means that 86.71% of referents are present on average

presentness_age<-presentness %>%
  filter(is.na(ref_predicted)==FALSE) %>%
  group_by(age) %>%
  summarise(mean=(sum(ref_predicted)/n()))

anova<-aov(mean ~ age, data=presentness_age)
#significant!! 
summary(anova)
```

```{r look at presentness refs}
present_ref<-presentness %>%
  group_by(referent, ref_predicted) %>%
  summarise(ref_count= sum(n())) %>%
  group_by(referent, ref_count, ref_predicted) %>%
  summarise(n = (ref_predicted*ref_count), count=ref_count) %>%
  group_by(referent) %>%
  summarise(prop_pres=sum(n)/sum(count)) %>%
  left_join(referents) 

ggplot(aes(x=freq, y=prop_pres), data=present_ref) +
  geom_point() +
  geom_smooth() #don't seem to be any frequency effects which is interesting

```

```{r}
presentness_kids <- presentness %>%
  group_by(subj, ref_predicted) %>%
  summarise(ref_count=sum(n())) %>%
  group_by(subj, ref_count, ref_predicted) %>%
  summarise(n = (ref_predicted*ref_count), count=ref_count) %>%
  group_by(subj) %>%
  summarise(prop= sum(n)/sum(count))
#kids seem to be pretty similar

presentness_person<-presentness %>%
  group_by(person, age, ref_predicted) %>%
  summarise(ref_count=sum(n())) %>%
  group_by(person, age, ref_count, ref_predicted) %>%
  summarise(n=(ref_predicted*ref_count), count=ref_count) %>%
  group_by(person, age) %>%
  summarise(prop=sum(n)/sum(count)) %>%
  mutate(person2=ifelse(person=="child", 1, 0))

#doesn't seem to be a person difference--let's make sure:
t.test(prop~person2, data=presentness_person)
#not significant 

#what about person differences by referent? Maybe parents always talk about some things that are not present but kids only talk about them when they are present
presentness_ref <- presentness %>%
  group_by(person, referent, ref_predicted) %>%
  summarise(ref_count=sum(n())) %>%
  group_by(person, referent, ref_count, ref_predicted) %>%
  summarise(n=(ref_predicted*ref_count), count=ref_count) %>%
  group_by(person, referent) %>%
  summarise(prop=sum(n)/sum(count)) %>%
  arrange(referent) %>%
  mutate(person2=ifelse(person=="child", 1, 0))
#it looks like all these proportions are pretty similar for parent and child by referent 

t.test(prop~person2, data=presentness_ref)
#nope, no difference!

```

Are there any differences with speech production probability and presentness? 
```{r}
#BROKEN DONT LOOK AT 
plotting_data <- coded_responses %>%
  mutate(ref_predicted=as.numeric(ref_predicted)) %>%
  mutate(ifelse(referent %in% present_ref$referent, present_ref$prop_pres, 500)) %>%
  group_by(person, age, subj, prop, modality) %>%
  summarise(n = n()) %>%
  mutate(prob = n/sum(n)) %>%
  group_by(person, age, modality, prop) %>%
  tidyboot_mean(prob)
```

